### ISSUE TITLE
Making the navigation menu bar fixed

### ISSUE THREAD

**Issue by Amenawon** [ifmeorg/ifme#2271] opened 2024-01-09 23:56 UTC
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is there a pain point in the app driving this feature request?

It might be a good UX to have the menu navigation fixed as the user scrolls

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the if-me community

**Comment by shivansh84ya** [comment] 2024-07-01 14:22
I would like to work on this issue. Could you please assign it to me?

Thanks!

**Comment by julianguyen** [comment] 2024-07-07 16:49
Closing this as this is a duplicate of https://github.com/ifmeorg/ifme/issues/2155

**Closed by julianguyen** 2024-07-07 16:49 UTC
