### ISSUE TITLE
navbar is not sticky

### ISSUE THREAD

**Issue by amitp138** [ifmeorg/ifme#2155] opened 2022-10-08 07:41 UTC
# Description
navbar of the website is not sticky that means it is not fixed due to which we have to scroll up for selecting any link from the navbar 

# Reproduction Steps

I can make the navbar sticky with responsiveness

# Screenshots

![image](https://user-images.githubusercontent.com/86116926/194696081-8ad77579-d3a5-40e9-854f-4fc798cb2321.png)

above we can see that navbar is not visible once we scroll down

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by julianguyen** [comment] 2022-10-08 14:59
Thanks for creating an issue with us! I think this could be a nice improvement. I think we'll want to talk through the design of this more. 

The different experiences we'll want to consider:
* Mobile web
* Signed-in
* Signed-out


The background of the sticky nav bar could have the same one as the mobile experience:

![image](https://user-images.githubusercontent.com/3010728/194713797-f1d22294-e2c2-418d-bcb0-c81d6f2910e4.png)

**Comment by saminarp** [comment] 2022-10-08 18:51
I am going to try fixing this issue, so I am assigning this to myself. :)

**Comment by amitp138** [comment] 2022-10-08 19:00
Then will I get the hactoberfest tag ??

**Comment by amitp138** [comment] 2022-10-09 07:50
so can you please give me the hactoberfest tag atleast

**Comment by amitp138** [comment] 2022-10-09 13:55
Hello @saminarp  can you please give me the hactoberfest tag please since I have raised this issue so I should be getting the chance right ??

**Comment by amitp138** [comment] 2022-10-11 08:57
Thank you sir for the consideration and also how can we discuss about this
like through the mail or anything else

**Comment by amitp138** [comment] 2022-10-12 22:52
hello @saminarp i am having issue while setting this up so if you want then you can continue with project

**Comment by SanjoyPator1** [comment] 2022-10-26 23:32
Is this issue fixed or Do you still need help?

**Comment by saminarp** [comment] 2022-10-26 23:42
I am still looking at it, and will keep it posted after I have updates

**Comment by amitp138** [comment] 2022-10-27 00:38
Ohk

**Comment by sfayyad** [comment] 2022-11-07 19:05
I would love to work on this! Can someone please assign it to me?

**Comment by Demandtech** [comment] 2023-02-20 12:40
I just check your website and I see the issue is still there, I will like to work on it.

**Comment by MuhammadAakash** [comment] 2023-03-06 11:34
@Demandtech Sure go ahead.

**Comment by Demandtech** [comment] 2023-03-06 11:41
Okay thank you I'm on it.

**Comment by MuhammadAakash** [comment] 2023-03-06 17:33
@Demandtech
Welcome, and If you have any questions or queries just ping us on Slack.

**Comment by thatsthat** [comment] 2023-07-07 09:49
Hi, I see this has been open for a long time and I'd like to help. @Demandtech did you manage to look into it?

**Comment by MuhammadAakash** [comment] 2023-07-08 12:06
Hi @thatsthat , I have assigned this issue to you. Please go ahead.

**Comment by shivansh84ya** [comment] 2024-07-01 14:25
I would like to work on this issue. Could you please assign it to me?
Thanks!

**Comment by julianguyen** [comment] 2024-07-07 16:48
Sure, assigned @shivansh84ya ! Thank you!

**Comment by julianguyen** [comment] 2024-07-08 01:56
I'm going to just finish this up since there have been many attempts to do this, and it would be great to close this out asap. Sorry about that!

**Closed** 2024-07-08 03:06 UTC
Labels: hacktoberfest, react, UX
