### ISSUE TITLE
Proofread and improve Chinese translations

### ISSUE THREAD

**Issue by julianguyen** [ifmeorg/ifme#1728] opened 2020-04-25 18:18 UTC
# Description

I reached out to my lovely friend @newpro (thank you!!!), who's also a software engineer, to improve our Chinese translations. He did a quick skim of them and noted there was room for improvement.

cc: @GayathriVenkatesh @Manasa2850 who worked on them initially

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

**Comment by newpro** [comment] 2020-04-26 20:40
## Reference Table for Chinese

### Objectives and Problems

The Chinese and English is not one to one mapping in this translation for two reasons. First, due to the cultural differences, the same word may have multiple meanings, refer to different positive/negative connotations apply to different situations, the small emotional differences may be significant in an app for emotional support. Second, many words establish at the "post-Internet" era, e.g., "feature", results in no direct translation from the old language like Chinese. I attempt to as the first Chinese translator for Ifme, a system should be established to bridge the gap as much as possible.

* `Enable open reviews for other members in org`: currently, there are limits amounts of translators for Chinese text. The table is established for the **non-Chinese speaker to check** if the messages are translated as intended. The reference table mainly allows the non-Chinese speakers to check on it by showing direct translation from Chinese back to English.
* `Establish future guideline or corrections`: the reference table is for **future Chinese translators to follow, or correct part of translation** to better alternatives. Notice that if you are one (welcome to the party!), and intent to correct part of concepts, make sure the concept consistency across all text, i.e., adjust all translations for the same concept.

### Concept Table

English | Chinese | Direct Translation Back | Note
--- | --- | --- | ---
category | 标签 | mark of tag |
mood | 心情 | what heart felt |
group| 小组 | little group | Alternative is 朋友圈 (circle of friend) but would overlap with allies
meeting | 会面 | Meet by face | alternative: 会议 (both face to face or meeting), but the word is to formal. Another alternative is 小聚 (meeting with friend) but mainly involve food.
draft | 计划, 草稿 | plan or draft of paper
privacy | 隐私条款 | notes of privacy
resources | 参考资料 | point of reference
code of conduct | 行为准则 | guide of behaviour
daily reminder | 每日提示 | daily hint
comment | 评论 | personal judgement and discussion
allies | 好友 | good friends | Alternative: 啦啦队 (cheerleaders) but may imbalanced to one gender
refill | 补药 | refill of medication
FAQ | 常见问题 | common questions
submit | 提交 | submit (internet word)
service | 服务功能 | service functions
loved one | 亲朋好友 | close families and friends | In Chinese culture "love" limits to romantic love of young people. People at personal level are separated as family, friend, or others.
notification | 提示 | hint | alternative: 通知 (public note) maybe too formal
stigmas | 问题 | problem | Direct translation of this word in Chinese is 耻辱 (shame) which is very strong word
Be you | 忠于自己 | be loyal to yourself | the concept of "self" associate with negative means like "selfish" in text (只想自己). And concept of "be" is equal to physically become (成为) which may not be a good translation.
viewer | 读者 | reader | alternative: 观众 (audience) which limits to audience of performance.
contribute | 贡献 | service by giving
Moment | 日记 | Diary | The current translation **has some problems**. "Diary" associated with daily recording, which may encourage users to only record once per day. This is the closest I can find, the direct translation is 时刻 which means everyday.
you, yours | 你的 | you/yours (informal) | Alternative: 您的 which is formal form, equal to "sir/madam".
(reported) users | 不良用户 | misbehave users
ban | 封号 | closed account
report | 投诉 | sue by user | alternative: 举报 which means submit to government as formal paper. 
group leader | 组长 | group elder (leader)
strategy | 健康规划 | plan of keeping health | The direct translation is "策略" which means "plan of attack"
help | 帮助 | assist
mental health workers | 精神健康专业人员 | mental health professionals | "workers" (工人) limits to people works in factory

## Main message

Main messages are important part of information to convey to public. Any differences of public messages are reported here.

English | Chinese | Direct Translation Back
--- | --- | --- 
Trusted allies are the people we interact with on a daily basis, including friends, family members, co-workers, teachers, and mental health workers. | 我们每天交流的人，包括朋友，家人，同事，老师和心理健康服务人员, 可以成为可信赖的好友。| People we are talking to everyday, including friends, families, colleges, teachers, health care professionals, can become trusted friends.
Dealing with mental health is what makes us human.But for a lot of us, it's a struggle to be open about it. | 处理心理健康的问题是我们生活的很重要的一部分。但是对于我们许多人来说, 开口分享心理健康的问题是很困难的。| Dealing with metal health problem is a very important part of life. But for many people, open up about it is very difficult.
Not everyone is a counsellor or therapist. The people who we interact with everyday shape our emotions and behaviour. |并非每个人都是精神健康顾问或心理学专家。我们每天相处的人会影响我们的情感和行为。鼓励他人参与心理健康治疗与活动是很重要的。| Not every one is psychologist or mental health consular. The people we been with can have impact on our emotions and behaviours.
It's not just all in your head, it's all around you. We can heal together.|为人处世,你的情感不仅在你的心理，也是影响你的周围。让我们一起健康吧。| When live in this world, your emotions are not only belongs to yourself, but also impacts people around you. Let us be healthy together.

## Other notes:

I did not change anything in the privacy policy part. This part contains a legal document that should be translated precisely in the legal context. E.g., "Access" is a legitimate word that I am not sure of the precise translation in Chinese. If you have a legal background who serves a future translator, you can attempt to correct it.

**Comment by newpro** [comment] 2020-04-27 12:22
The translations still have some room for improvement, preferably someone with Chinese language background can check on it in future. Close this for now. Keep up the good works and do not hesitate to ask for future help from me! :metal:

**Comment by julianguyen** [comment] 2020-05-01 21:38
Re-opening this issue to also review:
* https://github.com/ifmeorg/ifme/blob/master/config/locales/devise.zh-CN.yml
* https://github.com/ifmeorg/ifme/blob/master/config/locales/devise_invitable.zh-CN.yml
* https://github.com/ifmeorg/ifme/blob/master/config/locales/kaminari.zh-CN.yml

**Closed** 2020-05-10 17:56 UTC
Labels: translations
