### ISSUE TITLE
Users are not able to update their profille, updates are not getting saved in the profile section

### ISSUE THREAD

**Issue by developer22-university** [ifmeorg/ifme#1698] opened 2020-03-19 19:56 UTC
Users  cannot update their details in Customize profile section , it throws back  multiple errors while updating.

![Screenshot (108)](https://user-images.githubusercontent.com/51835554/77109211-87b27d80-6a49-11ea-9c0d-496cbb49d4ee.png)

1.) after clicking on update button it leads to  error page throwing a major error .which indicates the page connected to error is not working.

![Screenshot (107)](https://user-images.githubusercontent.com/51835554/77109218-8bde9b00-6a49-11ea-9416-e065fcb86ae0.png)
AS A CONSEQUENCE OF THIS ,THE USER DETAILS ARE NOT GETTING SAVED IN THE PROFILE SECTION AFTER GOING BACK. This major bug needs to be solved to enable the user to update it's profile, easily. This issue can be adressed after taking suggestions from mantainers. 

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!
Issue waiting for approval.

**Comment by developer22-university** [comment] 2020-03-19 20:00
@julianguyen  what do you think ? i have checked it after numerous test.
 user can update succesfully and save the details after solving this issue.

**Comment by developer22-university** [comment] 2020-03-19 20:00
i can go forward with it

**Comment by julianguyen** [comment] 2020-03-20 08:24
Sure, can you share the error log here? I'm unable to reproduce this issue in production and development.

**Comment by julianguyen** [comment] 2020-03-21 17:50
Based on our Slack conversation, it seems like this is related to your dev environment and missing environment variable setup. I'm going to close this issue for now. Let's sync on Slack over this!

**Closed by julianguyen** 2020-03-21 17:50 UTC
Labels: bug, ruby on rails, ui/ux
